### ISSUE TITLE
api装饰器只能判断响应值是JSON格式的情况

### ISSUE THREAD

**Issue by winhok** [SeldomQA/lounger#2]
有没有方法去解决
1. 当请求的响应值是一个页面时，如百度搜索后的响应值就是一个页面;
2. 当请求页面404没有响应值但是想判断状态码时
这两种情况，使api装饰器不仅仅只局限在有JSON响应值的请求中才能使用

**Comment by defnngj** [comment]
这个装饰主要是针对 http 接口，而且 返回值是 `JSON` 格式设计的。如果访问的是一个Web 页面，显然 `@api()` 装饰器不适用。
1. 你可以参考  `@api()` 装饰器 针对上述需求封装。
2. 贴出你的具体使用代码，我们来探讨。qq: 353332934
